# Nome do banco (crie no pgAdmin ou DBeaver antes)
spring.datasource.url=jdbc:postgresql://localhost:5432/chamados_db
spring.datasource.username=postgres
spring.datasource.password=123

# Cria as tabelas automaticamente (depois mudar para 'none')
spring.jpa.hibernate.ddl-auto=update

# Mostra os SQL no console 
spring.jpa.show-sql=true

# Porta do backend
server.port=8080